name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 185.173.104.142
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            exec > >(tee -a /var/log/deploy.log) 2>&1
            echo "Deployment started at $(date)"

            # Stop services
            systemctl stop fartak-backend.service
            systemctl stop fartak-frontend-next.service
            systemctl stop fartak-frontend-react.service

            # Update repo
            cd /root/FartakProjectService/ || exit
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            # Backend publish
            cd /var/www/fartak-backend/ || exit
            rm -rf ./*
            cd /root/FartakProjectService/backend/ || exit
            dotnet publish FartakProjectService/FartakProjectService.csproj -c Release -o /var/www/fartak-backend/

            # Frontend: Next
            cd /root/FartakProjectService/frontend/next/ || exit
            rm -rf node_modules .next
            npm install || echo "npm install failed (next)"
            npm run build || echo "Build failed for Next"

            # Frontend: React
            cd /root/FartakProjectService/frontend/react/ || exit
            rm -rf node_modules
            npm install || echo "npm install failed (react)"

            # Start services
            systemctl start fartak-backend.service
            systemctl start fartak-frontend-next.service
            systemctl start fartak-frontend-react.service

            # Check status
            systemctl status fartak-backend.service
            systemctl status fartak-frontend-next.service
            systemctl status fartak-frontend-react.service
